version: '2'
services:
  counter:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - redis
  redis:
    image: redis:3.2.5-alpine
    container_name: redis
    ports:
     - "6379:6379"
